SECOND_REMIND_TIME = 5
THIRD_REMIND_TIME = 15
LAST_REMIND_TIME = 30
EXPIRED_REMIND_TIME = LAST_REMIND_TIME + 1
DATETIME_FORMAT = '%Y-%m-%d %H:%M:00'

# Date/time format for week
START_WEEK_FORMAT = '%Y-%m-%d 00:01:00'
END_WEEK_FORMAT = '%Y-%m-%d 23:59:00'

# List flags
LIST_ALL_FLAG = 'all'
LIST_WEEK_FLAG = 'week'
