SECOND_REMIND_TIME = 5
THIRD_REMIND_TIME = 15
LAST_REMIND_TIME = 30
EXPIRED_REMIND_TIME = LAST_REMIND_TIME + 1
DATETIME_FORMAT = '%Y-%m-%d %H:%M:00'

# Date/time format for week
START_WEEK_FORMAT = '%Y-%m-%d 00:01:00'
END_WEEK_FORMAT = '%Y-%m-%d 23:59:00'

# List flags
LIST_ALL_FLAG = 'all'
LIST_WEEK_FLAG = 'week'

HOUR = 60

### Callback data

# LIST_BUTTON
LIST_ALL_BUTTON= 'list_all'
LIST_WEEK_BUTTON = 'week'
LIST_10_BUTTON = 'list_10'
LIST_3_BUTTON = 'list_3'

# DONE_BUTTON
DONE_BUTTON = 'done'

# POSTPONE_BUTTON
POSTPONE_30M_BUTTON = 'postpone_30m'
POSTPONE_1H_BUTTON = 'postpone_1h'